services:
  metric-writer:
    build: ./metricwriter
  grafana:
    image: "grafana/grafana-oss:10.4.0"
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
  postgres:
    image: "postgres:16.2"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql
  mqttbroker:
    image: "eclipse-mosquitto:2"
    ports:
      - "1883:1883"
      - "9001:9001"
    configs:
      - source: mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
  openhub:
    image: "openhab/openhab:4.1.1"
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      CRYPTO_POLICY: "unlimited"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Warsaw"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"

volumes:
  grafana-data:
  postgres-data:

configs:
  mosquitto.conf:
    content: |
      listener 1883
      allow_anonymous true